### PR TITLE
add extra camera settings to README.md

### PR DESCRIPTION
**Pull request by si458**
this just helps other users with extra values that can be set per camera

### CODE REVIEW

**Comment by QuantumEntangledAndy** [comment]
Not sure I want all of these in the readme the splash and debug stuff for example might not last through the next version

**Comment by QuantumEntangledAndy** [comment]
Which of these were actually useful for you?

**Comment by si458** [comment]
to be honest, i only did this PR because when i was fixing my other PR i noticed these extra values in the MQTT
and i couldnt work out what they did?
they was nowhere listed in the readme or docs
but a quick search in the issues and found what they each did,
so i through it would be best to add them in for others to see/maybe use

**Comment by Senbei123** [comment]
Thanks for the hints @si458; I add it to the configuration!

**Comment by QuantumEntangledAndy** [comment]
Sorry for the delay on this I kind of got lost in other things. Since it seems some people find it useful I'll merge it in but these might get removed in future updates

**Pull request merged**
