### PR TITLE
Improve MQTT documentation, example config

### PR DESCRIPTION
**Pull request by kevin-david**
Also print an error message when the configuration isn't present but the `mqtt` subcommand is used. Without this, the program just exits without any messages.

Finally, add a `launch.json` for VS code. I use this locally, and it would be handy with codespaces, but happy to stash it somehow instead

### CODE REVIEW

**Comment by kevin-david** [comment]
@QuantumEntangledAndy what's the state of the MQTT support right now? I've seen some weird behavior so far ...
- when a camera disconnects the app to be permanently scrogged / needs restarted
- there was at least one case where I got into an infinite loop that was writing to my MQTT broker

**Comment by QuantumEntangledAndy** [comment]
I am not 100% sure most of this I wrote years ago. I've only recently got back into programming neolink stuff. if you want to tackle it please do it could probably use a rewrite to something more stable.

Also could you remove the `.vscode/launch.json` since it not exactly related to the code and other devs may want to have their own launch configs

**Comment by kevin-david** [comment]
@QuantumEntangledAndy removed - BTW, it looks like the formatter builds might have been broken since `ubuntu-latest` is 22.04 now instead of 20.04

**Comment by QuantumEntangledAndy** [comment]
Yeah I think the style checks needs some work, I'll add it to my list of things to check. I have the clippy issues fixed in my latest unpublished work. My current to do list:

- Fix pause/resume on rtsp
- Fix mqtt
- Update gstreamer to latest
- Update build machines to latest os
- Put docker images on debian
- fix style checks
- Add formal version numbers and releases

So might take awhile to get to all that.

**Comment by QuantumEntangledAndy** [comment]
How is the flood light stuff? If you add the xml structures to the xml.rs it should be able to seralise and deserialise them without any other changes. Then you can send the messages like we do in logout.rs by adding a new function to camera and sending the packets.

**Comment by kevin-david** [comment]
I was able to get it sort of working... draft PR here: https://github.com/QuantumEntangledAndy/neolink/pull/14. I may take another look at this today.

Very new to Rust so having to learn the syntax as I go 😄

**Pull request merged**
