### PR TITLE
Fix/ptz stop

### LINKED ISSUE #71: "stop" PTZ Command missing
To provide some background to my issue, PTZ control over MQTT was not working for me prior to the recent update to this repo  involving updating MQTT to use tokio (I think?). However, after this update PTZ over MQTT seemed to be working somewhat reliably. However the camera seems to endlessly rotate no matter the speed. After some investigation with Wireshark and the Reolink desktop application, it seems that a 'stop' direction is sent when the user stops applying input to the PTZ commands.

To reproduce, I simply send a currently implemented PTZ command with MQTT, and the camera pans the expected way, although entirely to its limit unable to stop at a desired location.

Expected behavior should be that either the camera pans a specified amount before stopping, or a follow-up stop message should be sent by the user to cease the camera's motion. 

Forgive me if I have missed something here, or I am using the software incorrectly in some way, as I've only just started to play around with Neolink within the past week or so. I may try and implement this myself over the weekend if no one has the time.

### PR DESCRIPTION
**Pull request by AdrianosBates**
Everything seems to be working as intended, and I am now able to stop my camera using MQTT after issuing a PTZ command. The code changes are relatively minor, but I am not very familiar with Rust. 
On a slightly related note, I added the unrecognized command to the error message and found that an 'ok' MQTT message is being passed through after every PTZ MQTT message, although I'm not familiar with how the MQTT works so I can't say why this is.

Fix #71

### CODE REVIEW

**Comment by QuantumEntangledAndy** [comment]
Do you think t would be better if instead of issueing start/stop we instead did it as move amount. Where we get neolink to issue the stop itself after the right time.

**Comment by AdrianosBates** [comment]
Technically this is the native way that Reolink implements the commands, but I think that in the context of sending MQTT commands it would make sense to perhaps provide another variable for a move amount, or how long the camera should move. Also, the currently existing speed/amount variable seems to have no effect, but maybe that's just my camera. 

I think the simplest way would be to include a seconds variable for how long to move the camera, can you issue multiple arguments with MQTT or would you have to move each direction into a new topic?

**Comment by AdrianosBates** [comment]
As suggested, I have committed my (perhaps naïve) implementation of the above functionality. It seems to work well in my testing and is much easier to control.

**Comment by QuantumEntangledAndy** [comment]
Rather than seconds can we do distance like this.

ptz up distance speed

Speed should be optional at 32

Internally we convert distance to a time so the code can mostly be the same

time = distance / speed

Sorry I can't do this myself my laptop need to get repaired so I can't code much for a week.

Also with the current code we sleep the camera control thread. This means we can't get process any new new message util after it is done. This has some advantages such as stopping simultaneous moves and being able to wait for an OK when it is done but it might cause issues. When I get my laptop back I'm thinking to move the ptz onto a thread and using some sort of locking to stop simultaneous moving. But doing this means we get OK back straight away even if PTZ fails.

**Comment by AdrianosBates** [comment]
No worries, I appreciate the input and I'm glad to make any changes I'm capable of. I'm not very familiar with async code, especially with how it's implemented in neolink so I figured there might be some issue with sleeping the thread.  
I'll test a bit make these changes soon.

**Comment by QuantumEntangledAndy** [comment]
Probably want something like this;

```rust
tokio::task::spawn(async move {
//code to send start move
//code to sleep
//code to send stop 
};

**Comment by QuantumEntangledAndy** [comment]
Did you make any more progress with this? If you have any issues with the rust/async you could share them and I'll try to help.

**Comment by QuantumEntangledAndy** [comment]
I pushed some commits that should allow us to sleep by moving all the mqtt messages into their own seperate async task.

I also made the commands work based on distance rather than speed and time should be more intuitive

works like

`control/ptz down`
`control/ptz down 10`

default movement it 32 smallest is 1

**Comment by QuantumEntangledAndy** [comment]
@AdrianosBates I am planning to merge it with my changes unless there is something you want to add?

**Comment by AdrianosBates** [comment]
All good with me. Thanks for picking this up. Did you happen to figure out why 'ok'  messages where being passed through to MQTT during your time with this? Perhaps a different issue to be opened if not.

**Comment by QuantumEntangledAndy** [comment]
Yeah it is the reply on success (ok and fail on error), I need to filter out the replies

**Comment by QuantumEntangledAndy** [comment]
Is there a standard way to report success/fail in mqtt? I am not too familiar with what else is done with it

**Comment by QuantumEntangledAndy** [comment]
Ok I have got the filter in now. I will wait for the checks to pass one last time then merge. Thanks for your help here.

I don't suppose your camera has zoom? I'd like to get the controls for zoom but none of my cameras have it

**Comment by QuantumEntangledAndy** [comment]
Ok it's in master, i'll make a new release for this as 0.5.10

**Comment by QuantumEntangledAndy** [comment]
If you have any other ideas/fixes for neolink feel free to add/discuss them

**Comment by sanchosk** [comment]
@AdrianosBates Hi. Do you have any ko-fi account? I'd like to express my thanks for the fix that made the Reolink usable :)

**Comment by AdrianosBates** [comment]
> @AdrianosBates Hi. Do you have any ko-fi account? I'd like to express my thanks for the fix that made the Reolink usable :)

@sanchosk 
Sure, I've updated my GitHub profile. Although, @QuantumEntangledAndy deserves much of the credit for this and the entire updated repo.

> I don't suppose your camera has zoom? I'd like to get the controls for zoom but none of my cameras have it

@QuantumEntangledAndy 
Unfortunately not, although in the future I may end up buying the E1 Outdoor in which case I will check it out.

**Comment by QuantumEntangledAndy** [comment]
> Sure, I've updated my GitHub profile. Although, @QuantumEntangledAndy deserves much of the credit for this and the entire

He was kind enough to donate to me too, thought I'd drop your name too since you did most of the hard work for this PR. (Thank you very much to both of your help/support)

> Unfortunately not, although in the future I may end up buying the E1 Outdoor in which case I will check it out.

That would be great, I've had a few people use PT but noone actually owns a Z one. Theres also diagonal movements for UPLEFT etc but they don't seem to do anything on my camera.

Shoud also add the PTZ save and apply preset feature at some point to

**Pull request merged**
