### PR TITLE
Add many message_types

### PR DESCRIPTION
**Pull request by twistedddx**
Update body labels

### CODE REVIEW

**Comment by twistedddx** [comment]
I prefer the older naming style where the main xml tag name is used.
Most self explain what they are for.

**Comment by QuantumEntangledAndy** [comment]
These look good where to you find them all :)

**Comment by twistedddx** [comment]
Just used the official client and clicked things one by one.
All the XML is easy gotten via the same method.

**Comment by QuantumEntangledAndy** [comment]
I see more patience then me :), I was happy with just the ones on a login without clicking

**Pull request merged**
